# Generated by Django 4.2.11 on 2024-04-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_number',
            new_name='employee_id_number',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee',
            field=models.CharField(max_length=50),
        ),
    ]
